addSbtPlugin("com.itv" % "sbt-scalapact" % "2.3.4" withSources())
addSbtPlugin("com.itv" % "sbt-scalapact-nodeps" % "2.3.4")
addCompilerPlugin("org.scalamacros" % "paradise" % "2.1.0" cross CrossVersion.full)
addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "1.0.0" withSources())
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.9.0" withSources())